# Generated by Django 4.0.4 on 2022-04-28 18:04

from django.db import migrations, models
import django.db.models.deletion
import drf_settings.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=60)),
                ('name_en', models.CharField(max_length=60)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=drf_settings.helpers.UploadTo('category/'))),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=drf_settings.helpers.UploadTo('product'))),
                ('price', models.BigIntegerField()),
                ('available', models.IntegerField(default=0, verbose_name='Bazadagisoni')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
    ]
